### ISSUE TITLE
Links immediately expire (404)

### ISSUE THREAD

**Issue by atomheartother** [timvisee/send-docker-compose#2]
Hello,

I'm running this template for the first time, and as of right now everytime I upload a file it is impossible to access - any attempt to browse to the file's link displays a "link has expired" screen.

The file is displayed correctly on `mydomain.send.net`, along with "Expires in XX", but clicking it brings me to a "Link has expired" screen. More precisely, the call to `/downloads/XXX` always returns a 404.

My `uploads` directory does contain the newly uploaded file, and the ID seems to match so that's not the problem... Any idea of what the problem may be?

Feel free to debug here: https://send.navennec.net.

`docker-compose logs`:

```
send_1   | {"Timestamp":1611932387057000000,"Logger":"FirefoxSend","Type":"send.storage.Redis:","Severity":2,"Pid":1,"EnvVersion":"2.0","Fields":{"msg":"Retry time exhausted"}}
redis_1  | 1:C 29 Jan 2021 14:28:53.281 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
redis_1  | 1:C 29 Jan 2021 14:28:53.281 # Redis version=6.0.10, bits=64, commit=00000000, modified=0, pid=1, just started
redis_1  | 1:C 29 Jan 2021 14:28:53.281 # Warning: no config file specified, using the default config. In order to specify a config file use redis-server /path/to/redis.conf
redis_1  | 1:M 29 Jan 2021 14:28:53.282 * Running mode=standalone, port=6379.
redis_1  | 1:M 29 Jan 2021 14:28:53.282 # WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of 128.
redis_1  | 1:M 29 Jan 2021 14:28:53.282 # Server initialized
redis_1  | 1:M 29 Jan 2021 14:28:53.282 # WARNING overcommit_memory is set to 0! Background save may fail under low memory condition. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
redis_1  | 1:M 29 Jan 2021 14:28:53.282 # WARNING you have Transparent Huge Pages (THP) support enabled in your kernel. This will create latency and memory usage issues with Redis. To fix this issue run the command 'echo madvise > /sys/kernel/mm/transparent_hugepage/enabled' as root, and add it to your /etc/rc.local in order to retain the setting after a reboot. Redis must be restarted after THP is disabled (set to 'madvise' or 'never').
```

Did I misconfigure something?

**Note:** I'm not running the server through nginx, but behind traefik, so it could be a redirect issue? But the URL is correct since it reaches Send's 404 page, so I don't know if that could be the problem.

**Comment by atomheartother** [comment]
My `docker-compose.yml`:

```yml
version: "3"

services:
  send:
    image: '${DOCKER_SEND_IMAGE}'
    restart: always
    ports:
      - '1234:1234'
    volumes:
      - ./uploads:/app/uploads
    environment:
      - VIRTUAL_HOST=${HOST}
      - VIRTUAL_PORT=1234
      - DHPARAM_GENERATION=false
      - NODE_ENV=production
      - BASE_URL=${SEND_BASE_URL}
      - PORT=1234
      - REDIS_HOST=redis

      # For local uploads storage
      - FILE_DIR=/app/uploads

    labels:
        - traefik.enable=true
        - traefik.docker.network=proxy_public
        - traefik.http.routers.send.entrypoints=websecure
        - traefik.http.routers.send.rule=Host(`send.navennec.net`)
        - traefik.http.routers.send.tls.certresolver=myhttpchallenge
    networks:
      - proxy
    links:
      - redis
  redis:
    image: 'redis:alpine'
    restart: always
    volumes:
      - send-redis:/data

volumes:
  send-redis:
  proxy-certs:
  proxy-vhost:
  proxy-html:

networks:
  proxy:
    external:
      name: traefik_proxy
```
